services:

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rapelle_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mon-projet-net

  backend:
    build:
      context: ./backend-rappelle
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rapelle_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - mon-projet-net
  frontend:
    build:
      context: ./RappelleAngularFrontEnd
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - mon-projet-net
volumes:
  db_data:
